# Workarea::UrlToken
#
# Provides a URL-safe random token field for Mongoid documents.
#
# Previously this included ActiveRecord::SecureToken, but Rails 7.2 changed
# has_secure_token to call query_attribute() inside the generated callback.
# query_attribute is ActiveRecord-only and does not exist on Mongoid documents,
# causing a NoMethodError on every model that included this concern.
#
# The implementation below reproduces the same interface without depending on
# ActiveRecord::SecureToken.
module Workarea::UrlToken
  extend ActiveSupport::Concern

  included do
    field :token, type: String
    index({ token: 1 }, { unique: true })
    before_validation :ensure_token_exists
  end

  module ClassMethods
    def find_by_token(token)
      find_by(token: token) rescue nil
    end

    # Mimics ActiveRecord::SecureToken.generate_unique_secure_token
    def generate_unique_secure_token(length: 24)
      require 'active_support/core_ext/securerandom'
      SecureRandom.base58(length)
    end
  end

  # Mimics the regenerate_<attribute> method generated by has_secure_token
  def regenerate_token
    update!(token: self.class.generate_unique_secure_token)
  end

  private

  def ensure_token_exists
    self.token = self.class.generate_unique_secure_token if token.blank?
  end
end
