#!/usr/bin/env bash

echo "*************************************************************************"
echo "Running Bundler Audit..."
bundle exec bundle-audit check --update
rc=$?; if [[ $rc != 0 ]]; then exit $rc; fi

echo ""
echo ""
echo "*************************************************************************"
echo "Running Rubocop..."
bundle exec rubocop
rc=$?; if [[ $rc != 0 ]]; then exit $rc; fi

yarn init -yp --silent

echo ""
echo ""
echo "*************************************************************************"
echo "Running ESLint..."
yarn add --silent --dev eslint@4.19.1 --loglevel error
yarn run eslint admin/app/**/*.js admin/**/test/**/*.js core/app/**/*.js core/**/test/**/*.js storefront/app/**/*.js storefront/**/test/**/*.js
rc=$?; if [[ $rc != 0 ]]; then exit $rc; fi

echo ""
echo "*************************************************************************"
echo "Running Stylelint..."
yarn add --silent --dev stylelint@9.2.1 stylelint-scss@3.1.0 stylelint-config-recommended-scss@3.2.0
yarn run stylelint admin/app/**/*.scss core/app/**/*.scss storefront/app/**/*.scss
