#!/usr/bin/env bash

# Boots Workarea under the Rails 7.2 appraisal and captures the middleware stack.
#
# Usage:
#   ./scripts/rails_7_2_middleware_snapshot.sh
#
# Output:
#   docs/rails_7_2_middleware.txt

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT_FILE="$ROOT_DIR/docs/rails_7_2_middleware.txt"

cd "$ROOT_DIR"

# Ensure we write the new snapshot atomically.
TMP_FILE="$(mktemp -t rails_7_2_middleware.XXXXXX)"
trap 'rm -f "$TMP_FILE"' EXIT

RBENV_PREFIX=()
if command -v rbenv >/dev/null 2>&1; then
  # Ensure rbenv uses the repo-pinned Ruby even in non-interactive shells.
  if [[ -f "$ROOT_DIR/.ruby-version" ]]; then
    export RBENV_VERSION
    RBENV_VERSION="$(cat "$ROOT_DIR/.ruby-version")"
  fi
  RBENV_PREFIX=(rbenv exec)
fi

{
  echo "# Workarea Rails 7.2 middleware snapshot"
  echo "#"
  echo "# Generated by: ./scripts/rails_7_2_middleware_snapshot.sh"
  echo "# Command: BUNDLE_GEMFILE=gemfiles/rails_7_2.gemfile bundle exec core/test/dummy/bin/rails middleware"
  echo "# Generated at: $(date -u '+%Y-%m-%dT%H:%M:%SZ')"
  echo ""
  BUNDLE_GEMFILE=gemfiles/rails_7_2.gemfile "${RBENV_PREFIX[@]}" bundle exec core/test/dummy/bin/rails middleware
} > "$TMP_FILE"

mv "$TMP_FILE" "$OUT_FILE"

echo "Wrote middleware snapshot to: $OUT_FILE"