source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

gem 'redcarpet', '~> 3.5.0'
gem 'middleman', '~> 4.3.5'
gem 'middleman-autoprefixer', '~> 2.10.1'
gem 'middleman-search', github: 'workarea-commerce/middleman-search'
gem 'middleman-navtree', '~> 0.1.10'
gem 'puma', '~> 4.1.1'
